---
- name: Install CUDA Toolkit 12.5
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  vars:
    cuda_home: "/usr/local/cuda"  # Adjust this path as needed
  tasks:
    - name: Remove problematic CUDA repository files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/cuda-ubuntu2204-12-5-local.list
        - /var/cuda-repo-ubuntu2204-12-5-local

    - name: Update apt cache
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Ensure wget and gnupg are installed
      apt:
        name: 
          - wget
          - gnupg
        state: present
        update_cache: yes

    - name: Download CUDA repository pin file
      command: wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin -O /tmp/cuda-ubuntu2204.pin
      args:
        creates: /tmp/cuda-ubuntu2204.pin

    - name: Move CUDA pin file to preferences.d
      command: mv /tmp/cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600

    - name: Download CUDA GPG key
      command: wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub -O /tmp/cuda-repo.pub
      args:
        creates: /tmp/cuda-repo.pub

    - name: Import CUDA GPG key
      apt_key:
        file: /tmp/cuda-repo.pub
        state: present

    - name: Download CUDA 12.5 repository package
      command: wget https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb -O /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
      args:
        creates: /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb

    - name: Install CUDA repository package
      apt:
        deb: /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb

    - name: Find CUDA keyring file
      find:
        paths: /var/cuda-repo-ubuntu2204-12-5-local
        patterns: 'cuda-*-keyring.gpg'
      register: cuda_keyring_file

    - name: Copy CUDA keyring
      command: cp "{{ cuda_keyring_file.files[0].path }}" /usr/share/keyrings/
      when: cuda_keyring_file.matched > 0

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install CUDA Toolkit 12.5
      apt:
        name: cuda-toolkit-12-5
        state: present

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/cuda-ubuntu2204.pin
        - /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
        - /tmp/cuda-repo.pub
  
    - name: Check if .zshrc exists
      stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc_file

    - name: Check if .bashrc exists
      stat:
        path: "{{ ansible_env.HOME }}/.bashrc"
      register: bashrc_file

    - name: Add CUDA_HOME to .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "export CUDA_HOME={{ cuda_home }}"
        regexp: '^export CUDA_HOME='
        state: present
      when: zshrc_file.stat.exists

    - name: Add CUDA_HOME to .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export CUDA_HOME={{ cuda_home }}"
        regexp: '^export CUDA_HOME='
        state: present
      when: bashrc_file.stat.exists

    - name: Add CUDA bin to PATH in .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "export PATH=$CUDA_HOME/bin:$PATH"
        regexp: '^export PATH=\$CUDA_HOME/bin:\$PATH'
        state: present
      when: zshrc_file.stat.exists

    - name: Add CUDA bin to PATH in .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export PATH=$CUDA_HOME/bin:$PATH"
        regexp: '^export PATH=\$CUDA_HOME/bin:\$PATH'
        state: present
      when: bashrc_file.stat.exists

    - name: Add LD_LIBRARY_PATH in .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH"
        regexp: '^export LD_LIBRARY_PATH=\$CUDA_HOME/lib64:\$LD_LIBRARY_PATH'
        state: present
      when: zshrc_file.stat.exists

    - name: Add LD_LIBRARY_PATH in .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH"
        regexp: '^export LD_LIBRARY_PATH=\$CUDA_HOME/lib64:\$LD_LIBRARY_PATH'
        state: present
      when: bashrc_file.stat.exists
  