---
- name: Install CUDA Toolkit 12.5
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download CUDA repository pin file
      command: wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin -O /tmp/cuda-ubuntu2204.pin
      args:
        creates: /tmp/cuda-ubuntu2204.pin

    - name: Move CUDA pin file to preferences.d
      command: mv /tmp/cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600

    - name: Download CUDA 12.5 repository package
      command: wget https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb -O /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
      args:
        creates: /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb

    - name: Install CUDA repository package
      apt:
        deb: /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb

    - name: Copy CUDA keyring
      command: cp /var/cuda-repo-ubuntu2204-12-5-local/cuda-*-keyring.gpg /usr/share/keyrings/

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install CUDA Toolkit 12.5
      apt:
        name: cuda-toolkit-12-5
        state: present

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/cuda-ubuntu2204.pin
        - /tmp/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
  